include: package:a2f_sdk/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
  errors:
    no_runtimetype_tostring: ignore
    await_only_futures: warning
    unawaited_futures: warning
linter:
  rules:
    public_member_api_docs: true
