name: wayt_app_workspace
sdkPath: .fvm/flutter_sdk

packages:
  - wayt_app

scripts:
  analyze:
    exec: fvm dart analyze .

  fix:
    exec: fvm dart fix ./lib --apply && fvm dart format ./lib

  clean-hard:
    run: |-
      echo "🚿 Deep clean in progress..."
      fvm flutter clean

      echo "🗑️ Removing symlinks and Pods..."
      rm -rf wayt_app/ios/.symlinks
      rm -rf wayt_app/ios/Pods
      rm -f wayt_app/ios/Podfile.lock
      rm -f wayt_app/pubspec.lock

      echo "📦 Getting dependencies..."
      fvm flutter pub get

      echo "📲 Installing CocoaPods..."
      fvm flutter precache --ios
      cd wayt_app/ios && pod install --repo-update
      
    packageFilters:
      scope: wayt_app

  generate:
    run: |-
      fvm dart run build_runner build --delete-conflicting-outputs
      dart run flutter_iconpicker:generate_packs --packs material
    exec: 
      concurrency: 1
      orderDependents: true
    description: Build all generated files for Dart & Flutter packages in this project.
    packageFilters:
      dependsOn: build_runner
  generate-env:
    run: fvm dart run build_runner clean && fvm dart run build_runner build --delete-conflicting-outputs
    exec: 
      concurrency: 1
      orderDependents: true
    description: Build all env generated files for Dart & Flutter packages in this project.
    packageFilters:
      dependsOn: envied_generator
