name: wayt_app_workspace
sdkPath: .fvm/flutter_sdk

packages:
  - wayt_app

scripts:
  analyze:
    exec: fvm dart analyze .

  fix:
    exec: fvm dart fix ./lib --apply && fvm dart format ./lib

  generate:
    run: |-
      fvm dart run build_runner build --delete-conflicting-outputs
      dart run flutter_iconpicker:generate_packs --packs material
    exec: 
      concurrency: 1
      orderDependents: true
    description: Build all generated files for Dart & Flutter packages in this project.
    packageFilters:
      dependsOn: build_runner
  generate-env:
    run: fvm dart run build_runner clean && fvm dart run build_runner build --delete-conflicting-outputs
    exec: 
      concurrency: 1
      orderDependents: true
    description: Build all env generated files for Dart & Flutter packages in this project.
    packageFilters:
      dependsOn: envied_generator
