targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/**.gen.dart
        options:
          field_rename: snake
          create_to_json: true
          generic_argument_factories: true
      envied_generator|envied:
        generate_for:
          include:
            - lib/env/**.gen.dart
