name: wayt_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  a2f_sdk:
    git:
      url: git@github.com:app-anvil/a2f_sdk.git
      ref: 7.0.0
  bloc: ^8.1.4
  envied: ^1.0.0
  equatable: ^2.0.7
  flext: ^1.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_iconpicker: ^4.0.1
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.1
  gap: ^3.0.1
  get_it: ^8.0.2
  go_router: ^14.6.1
  intl: ^0.19.0
  luthor: ^0.5.2+1
  path: ^1.9.0
  pub_semver: ^2.1.5
  the_umpteenth_logger:
    git:
      url: git@github.com:gianmarcocalbi/the_umpteenth_logger.git
      path: packages/the_umpteenth_logger
      ref: 1.1.0
  uuid: ^4.5.1
  world_countries: ^2.0.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: 'Noto Sans'
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans/NotoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/noto_sans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans/NotoSans-MediumItalic.ttf
          style: italic
          weight: 500
    - family: 'Noto Serif'
      fonts:
        - asset: assets/fonts/noto_serif/NotoSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_serif/NotoSerif-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/noto_serif/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_serif/NotoSerif-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/noto_serif/NotoSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_serif/NotoSerif-MediumItalic.ttf
          style: italic
          weight: 500
