name: 1.0.0-alpha.2:feat:mobile
description: 1.0.0-alpha.2:feat:mobile
title: 'feat: '
labels: ["p • mobile \U0001F4F1"]
projects: ['wayt-travel/9']
type: '💡 Feature'
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
